PATH_ENTER_RETRIES = 5

TIMEOUT = 20
MAX_CONCURRENT_DOWNLOADS = 3
MAX_FILE_SIZE = 5 * 1024 *1024 # 5 MB
DOWNLOAD_RETRIES = 3

DEFAULT_DOWNLOAD_DIR = "../downloads"
DEFAULT_LINKS_FILE = "links.txt"
DEFAULT_LOG_FILE = "downloader.log"